#!/usr/bin/env bash

HEXTUNNEL_SSH_MODE_STATE="${HEXTUNNEL_SSH_MODE_STATE:-$HEXTUNNEL_STATE/ssh-socket.state}"

ssh_capture_socket_mode() {
  local socket_enabled=0 socket_active=0 service_enabled=0 service_active=0

  [[ -f "$HEXTUNNEL_SSH_MODE_STATE" ]] && return 0
  systemctl cat ssh.socket >/dev/null 2>&1 || return 0

  systemctl is-enabled --quiet ssh.socket 2>/dev/null && socket_enabled=1
  systemctl is-active --quiet ssh.socket 2>/dev/null && socket_active=1
  ((socket_enabled || socket_active)) || return 0

  systemctl is-enabled --quiet ssh.service 2>/dev/null && service_enabled=1
  systemctl is-active --quiet ssh.service 2>/dev/null && service_active=1

  write_file "$HEXTUNNEL_SSH_MODE_STATE" 600 <<EOF
socket_enabled=$socket_enabled
socket_active=$socket_active
service_enabled=$service_enabled
service_active=$service_active
EOF
}

ssh_switch_to_service_mode() {
  [[ -f "$HEXTUNNEL_SSH_MODE_STATE" ]] || return 0

  record_service_state ssh.socket
  record_service_state ssh.service
  run_cmd systemctl disable --now ssh.socket || true
  safe_restart_service ssh "sshd -t"

  if [[ "${HEXTUNNEL_DRY_RUN:-0}" != 1 ]]; then
    port_is_listening tcp 22 || die "OpenSSH dejó de escuchar en tcp/22 al desactivar ssh.socket."
    port_is_listening tcp 299 || die "OpenSSH no abrió tcp/299 en modo ssh.service."
  fi
}

ssh_restore_socket_mode() {
  local socket_enabled=0 socket_active=0 service_enabled=0 service_active=0
  [[ -f "$HEXTUNNEL_SSH_MODE_STATE" ]] || return 0

  # This file is generated by Hex Tunnel with numeric values only.
  # shellcheck disable=SC1090
  source "$HEXTUNNEL_SSH_MODE_STATE"

  backup_path "$HEXTUNNEL_SSH_MODE_STATE"
  record_service_state ssh.service
  record_service_state ssh.socket

  run_cmd systemctl stop ssh.service || true

  if [[ "$service_enabled" == 1 ]]; then
    run_cmd systemctl enable ssh.service
  else
    run_cmd systemctl disable ssh.service || true
  fi

  if [[ "$socket_enabled" == 1 ]]; then
    run_cmd systemctl enable ssh.socket
  else
    run_cmd systemctl disable ssh.socket || true
  fi

  if [[ "$socket_active" == 1 ]]; then
    run_cmd systemctl start ssh.socket
  else
    run_cmd systemctl stop ssh.socket || true
  fi

  if [[ "$service_active" == 1 ]]; then
    run_cmd systemctl start ssh.service
  fi

  if [[ "${HEXTUNNEL_DRY_RUN:-0}" != 1 ]]; then
    rm -f "$HEXTUNNEL_SSH_MODE_STATE"
    if [[ "$socket_active" == 1 || "$service_active" == 1 ]]; then
      port_is_listening tcp 22 || die "OpenSSH no restauró tcp/22 después de desinstalar el módulo."
    fi
  fi
}
