#!/usr/bin/env bash
normalize_architecture() { case "$(uname -m)" in x86_64|amd64) printf amd64 ;; aarch64|arm64) printf arm64 ;; armv7l|armv7*) printf arm ;; i386|i486|i586|i686) printf 386 ;; *) return 1 ;; esac; }
validate_operating_system() { [[ -r /etc/os-release ]] || die "No se pudo leer /etc/os-release."; source /etc/os-release; case "${ID:-}:${VERSION_ID:-}" in debian:11|debian:12|ubuntu:20.04|ubuntu:22.04|ubuntu:24.04) ;; *) die "Sistema no soportado: ${ID:-desconocido} ${VERSION_ID:-}." ;; esac; }
validate_resources() { local mem_kb disk_kb; mem_kb="$(awk '/MemTotal/ {print $2}' /proc/meminfo)"; disk_kb="$(df -Pk / | awk 'NR==2 {print $4}')"; ((mem_kb >= ${HEXTUNNEL_MIN_RAM_KB:-524288})) || die "Se requieren al menos 512 MiB de RAM."; ((disk_kb >= ${HEXTUNNEL_MIN_DISK_KB:-1048576})) || die "Se requiere al menos 1 GiB libre en /."; }
validate_connectivity() { local url; for url in https://github.com https://api.github.com https://1.1.1.1; do curl -fsSI --connect-timeout 5 --max-time 10 "$url" >/dev/null 2>&1 && return 0; done; die "No hay conectividad HTTPS utilizable."; }
port_is_listening() { local protocol="$1" port="$2"; if [[ "$protocol" == udp ]]; then ss -H -lun "sport = :$port" 2>/dev/null | grep -q .; else ss -H -ltn "sport = :$port" 2>/dev/null | grep -q .; fi; }
validate_requested_ports() { local module protocol port source owner; for module in "$@"; do while read -r protocol port source; do [[ -n "$protocol" && -n "$port" ]] || continue; if port_is_listening "$protocol" "$port"; then owner="$(ss -H -lntup "sport = :$port" 2>/dev/null | head -n1)"; [[ "${HEXTUNNEL_FORCE:-0}" == 1 ]] || die "El puerto $protocol/$port ya está ocupado: ${owner:-proceso desconocido}."; log_warn "Puerto ocupado permitido por --force: $protocol/$port"; fi; done < <(module_call "$module" ports || true); done; }
preflight_all() { require_root; command_exists systemctl || die "systemd/systemctl es obligatorio."; command_exists curl || die "curl es obligatorio."; command_exists ss || die "iproute2/ss es obligatorio."; validate_operating_system; HEXTUNNEL_ARCH="$(normalize_architecture)" || die "Arquitectura no soportada: $(uname -m)."; export HEXTUNNEL_ARCH; validate_resources; validate_connectivity; validate_requested_ports "$@"; log_success "Preflight correcto: OS, arquitectura, RAM, disco, red y puertos."; }
validate_selected_modules() { local module; for module in "$@"; do module_validate "$module"; done; }
